from . import A00HaydovchiMijoz
from . import A01HaydovchiQayerQatnov
from . import A02Haydovchi
from . import A03HaydovchiMashina
from . import A04HaydovchiQayerga
from . import A05HaydovchiVodiy
from . import A06HaydovchiQayerTuman
from . import A07HaydovchiKishiSoni
from . import A08TelRaqam
from . import A09Ismi
from . import A10Narhi
